//#define _ENABLE_LOGS_INFO_
//#define _ENABLE_LOGS_THREAD_INFO_
//#define _ENABLE_LOGS_THREAD_VERBOSE_
#define _ENABLE_LOGS_THREAD_ERR_
//#define _ENABLE_LOGS_INFO_TIME_
//#define _ENABLE_LOGS_VERBOSE_
#define _ENABLE_LOGS_ERR_
//#define _ENABLE_LOGS_INFO_RESULT_

